/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as RfqsRouteImport } from './routes/rfqs'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RfqsIdRouteImport } from './routes/rfqs.$id'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqsRoute = RfqsRouteImport.update({
  id: '/rfqs',
  path: '/rfqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqsIdRoute = RfqsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RfqsRoute,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InvoicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/rfqs': typeof RfqsRouteWithChildren
  '/vendors': typeof VendorsRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/rfqs/$id': typeof RfqsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/rfqs': typeof RfqsRouteWithChildren
  '/vendors': typeof VendorsRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/rfqs/$id': typeof RfqsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/rfqs': typeof RfqsRouteWithChildren
  '/vendors': typeof VendorsRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/rfqs/$id': typeof RfqsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/invoices'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/purchase-orders'
    | '/quotations'
    | '/reports'
    | '/rfqs'
    | '/vendors'
    | '/invoices/$id'
    | '/rfqs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/invoices'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/purchase-orders'
    | '/quotations'
    | '/reports'
    | '/rfqs'
    | '/vendors'
    | '/invoices/$id'
    | '/rfqs/$id'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/invoices'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/purchase-orders'
    | '/quotations'
    | '/reports'
    | '/rfqs'
    | '/vendors'
    | '/invoices/$id'
    | '/rfqs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  InvoicesRoute: typeof InvoicesRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  QuotationsRoute: typeof QuotationsRoute
  ReportsRoute: typeof ReportsRoute
  RfqsRoute: typeof RfqsRouteWithChildren
  VendorsRoute: typeof VendorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfqs': {
      id: '/rfqs'
      path: '/rfqs'
      fullPath: '/rfqs'
      preLoaderRoute: typeof RfqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfqs/$id': {
      id: '/rfqs/$id'
      path: '/$id'
      fullPath: '/rfqs/$id'
      preLoaderRoute: typeof RfqsIdRouteImport
      parentRoute: typeof RfqsRoute
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof InvoicesRoute
    }
  }
}

interface InvoicesRouteChildren {
  InvoicesIdRoute: typeof InvoicesIdRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesIdRoute: InvoicesIdRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

interface RfqsRouteChildren {
  RfqsIdRoute: typeof RfqsIdRoute
}

const RfqsRouteChildren: RfqsRouteChildren = {
  RfqsIdRoute: RfqsIdRoute,
}

const RfqsRouteWithChildren = RfqsRoute._addFileChildren(RfqsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  InvoicesRoute: InvoicesRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  QuotationsRoute: QuotationsRoute,
  ReportsRoute: ReportsRoute,
  RfqsRoute: RfqsRouteWithChildren,
  VendorsRoute: VendorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
